/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestGeographyGradeRouteImport } from './routes/test.geography.$grade'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestGeographyGradeRoute = TestGeographyGradeRouteImport.update({
  id: '/test/geography/$grade',
  path: '/test/geography/$grade',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test/geography/$grade': typeof TestGeographyGradeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test/geography/$grade': typeof TestGeographyGradeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test/geography/$grade': typeof TestGeographyGradeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/test/geography/$grade'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/test/geography/$grade'
  id: '__root__' | '/' | '/test/geography/$grade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestGeographyGradeRoute: typeof TestGeographyGradeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/geography/$grade': {
      id: '/test/geography/$grade'
      path: '/test/geography/$grade'
      fullPath: '/test/geography/$grade'
      preLoaderRoute: typeof TestGeographyGradeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestGeographyGradeRoute: TestGeographyGradeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
