/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayRouteImport } from './routes/play'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestSubjectGradeRouteImport } from './routes/test.$subject.$grade'

const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestSubjectGradeRoute = TestSubjectGradeRouteImport.update({
  id: '/test/$subject/$grade',
  path: '/test/$subject/$grade',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/play': typeof PlayRoute
  '/test/$subject/$grade': typeof TestSubjectGradeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/play': typeof PlayRoute
  '/test/$subject/$grade': typeof TestSubjectGradeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/play': typeof PlayRoute
  '/test/$subject/$grade': typeof TestSubjectGradeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/play' | '/test/$subject/$grade'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/play' | '/test/$subject/$grade'
  id: '__root__' | '/' | '/play' | '/test/$subject/$grade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayRoute: typeof PlayRoute
  TestSubjectGradeRoute: typeof TestSubjectGradeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$subject/$grade': {
      id: '/test/$subject/$grade'
      path: '/test/$subject/$grade'
      fullPath: '/test/$subject/$grade'
      preLoaderRoute: typeof TestSubjectGradeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayRoute: PlayRoute,
  TestSubjectGradeRoute: TestSubjectGradeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
